# fly.toml app configuration file generated for manglar on 2023-06-14T13:57:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "manglar"
primary_region = "bog"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
